"""initial model table

Revision ID: d83313ec81f9
Revises: 
Create Date: 2026-06-03 07:46:23.079808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd83313ec81f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('n_components', sa.Integer(), nullable=False),
    sa.Column('preprocessing', sa.JSON(), nullable=False),
    sa.Column('excluded_samples', sa.JSON(), nullable=False),
    sa.Column('params', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['model.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_parent_id'))

    op.drop_table('model')
    # ### end Alembic commands ###
